#pragma once 

#include <src/raze/datapar/bitwise/BitAnd.h>
#include <src/raze/datapar/bitwise/BitNot.h>
#include <src/raze/datapar/bitwise/BitOr.h>
#include <src/raze/datapar/bitwise/BitXor.h>
#include <src/raze/datapar/bitwise/MaskConvert.h>
#include <src/raze/datapar/bitwise/ToBitmask.h>
#include <src/raze/datapar/bitwise/ToMask.h>
#include <src/raze/datapar/bitwise/ToVector.h>
#include <src/raze/datapar/bitwise/BitmaskBitsPerElement.h>
#include <src/raze/datapar/bitwise/Testz.h>
#include <src/raze/datapar/bitwise/TestAllOnes.h>
#include <src/raze/datapar/bitwise/SimdBoolReference.h>
#include <src/raze/datapar/bitwise/BitReference.h>
#include <src/raze/datapar/bitwise/SimdElementReference.h>
#include <src/raze/datapar/bitwise/MaskIntrin.h>
#include <src/raze/datapar/bitwise/MaskElementReference.h>
#include <src/raze/datapar/bitwise/ToGPR.h>
#include <src/raze/datapar/bitwise/MaskBits.h>
#include <src/raze/datapar/bitwise/MaskOperations.h>
#include <src/raze/datapar/bitwise/FirstN.h>
#include <src/raze/datapar/bitwise/ToK.h>