#pragma once 

#include <src/raze/vx/arithmetic/Abs.h>
#include <src/raze/vx/arithmetic/MaskAbs.h>
#include <src/raze/vx/arithmetic/MaskzAbs.h>
#include <src/raze/vx/arithmetic/Add.h>
#include <src/raze/vx/arithmetic/MaskAdd.h>
#include <src/raze/vx/arithmetic/MaskzAdd.h>
#include <src/raze/vx/arithmetic/Div.h>
#include <src/raze/vx/arithmetic/MaskDiv.h>
#include <src/raze/vx/arithmetic/MaskzDiv.h>
#include <src/raze/vx/arithmetic/Mul.h>
#include <src/raze/vx/arithmetic/MaskMul.h>
#include <src/raze/vx/arithmetic/MaskzMul.h>
#include <src/raze/vx/arithmetic/Negate.h>
#include <src/raze/vx/arithmetic/MaskNegate.h>
#include <src/raze/vx/arithmetic/MaskzNegate.h>
#include <src/raze/vx/arithmetic/Sub.h>
#include <src/raze/vx/arithmetic/MaskSub.h>
#include <src/raze/vx/arithmetic/MaskzSub.h>
#include <src/raze/vx/arithmetic/VerticalMax.h>
#include <src/raze/vx/arithmetic/MaskVerticalMax.h>
#include <src/raze/vx/arithmetic/MaskzVerticalMax.h>
#include <src/raze/vx/arithmetic/VerticalMin.h>
#include <src/raze/vx/arithmetic/MaskVerticalMin.h>
#include <src/raze/vx/arithmetic/MaskzVerticalMin.h>
#include <src/raze/vx/arithmetic/MaskAssign.h>
#include <src/raze/vx/arithmetic/MaskzAssign.h>
#include <src/raze/vx/arithmetic/Fma.h>
#include <src/raze/vx/arithmetic/Fnma.h>
#include <src/raze/vx/arithmetic/Fms.h>
#include <src/raze/vx/arithmetic/Fnms.h>
#include <src/raze/vx/arithmetic/MaskFma.h>
#include <src/raze/vx/arithmetic/MaskFms.h>
#include <src/raze/vx/arithmetic/MaskFnma.h>
#include <src/raze/vx/arithmetic/MaskFnms.h>
#include <src/raze/vx/arithmetic/MaskzFma.h>
#include <src/raze/vx/arithmetic/MaskzFms.h>
#include <src/raze/vx/arithmetic/MaskzFnma.h>
#include <src/raze/vx/arithmetic/MaskzFnms.h>
