#pragma once 


#include <src/raze/vx/bitwise/Andnot.h>
#include <src/raze/vx/bitwise/MaskAndnot.h>
#include <src/raze/vx/bitwise/MaskzAndnot.h>
#include <src/raze/vx/bitwise/BitAnd.h>
#include <src/raze/vx/bitwise/MaskBitAnd.h>
#include <src/raze/vx/bitwise/MaskzBitAnd.h>
#include <src/raze/vx/bitwise/BitNot.h>
#include <src/raze/vx/bitwise/MaskBitNot.h>
#include <src/raze/vx/bitwise/MaskzBitNot.h>
#include <src/raze/vx/bitwise/BitOr.h>
#include <src/raze/vx/bitwise/MaskBitOr.h>
#include <src/raze/vx/bitwise/MaskzBitOr.h>
#include <src/raze/vx/bitwise/BitXor.h>
#include <src/raze/vx/bitwise/MaskBitXor.h>
#include <src/raze/vx/bitwise/MaskzBitXor.h>
#include <src/raze/vx/bitwise/MaskConvert.h>
#include <src/raze/vx/bitwise/ToBitmask.h>
#include <src/raze/vx/bitwise/ToMask.h>
#include <src/raze/vx/bitwise/ToVector.h>
#include <src/raze/vx/bitwise/BitmaskBitsPerElement.h>
#include <src/raze/vx/bitwise/Testz.h>
#include <src/raze/vx/bitwise/TestAllOnes.h>
#include <src/raze/vx/bitwise/SimdBoolReference.h>
#include <src/raze/vx/bitwise/BitReference.h>
#include <src/raze/vx/bitwise/SimdElementReference.h>
#include <src/raze/vx/bitwise/MaskIntrin.h>
#include <src/raze/vx/bitwise/MaskElementReference.h>
#include <src/raze/vx/bitwise/ToGPR.h>
#include <src/raze/vx/bitwise/MaskBits.h>
#include <src/raze/vx/bitwise/MaskOperations.h>
#include <src/raze/vx/bitwise/RightShift.h>
#include <src/raze/vx/bitwise/LeftShift.h>
#include <src/raze/vx/bitwise/FirstN.h>
#include <src/raze/vx/bitwise/ToK.h>
#include <src/raze/vx/bitwise/MaskLeftShift.h>
#include <src/raze/vx/bitwise/MaskRightShift.h>
#include <src/raze/vx/bitwise/MaskzLeftShift.h>
#include <src/raze/vx/bitwise/MaskzRightShift.h>
#include <src/raze/vx/bitwise/Ternarylogic.h>